// <auto-generated />
namespace TimeTracker_ng4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixstartdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixstartdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201711062009519_fix start date "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
